#!/bin/bash
#SBATCH --account punim2175
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=0-06:00:00
#SBATCH --mem=128G
#SBATCH --partition=sapphire
#SBATCH -o /data/gpfs/projects/punim2175/T-HEADS/scripts/slurm_logs/slurm-%N.%j.out
#SBATCH -e /data/gpfs/projects/punim2175/T-HEADS/scripts/slurm_errors/slurm-%N.%j.err

# Author: Remika Mito
# Date: 23 May 2025
# Description: This script runs steps 14-17 in FBA pipeline (computes fixels & FD, reorients, 
# assigns to template, and computes FC. logFC and FDC can be computed in command line

# check arguments are provided
if [ "$#" -ne 1 ]; then
  echo "Usage: slurm_TH_step09_fixel_poptemp_1_sites.script [ID]"
  exit 1
fi

# load modules
module load MRtrix/3.0.4

# specify inputs
ID=$1
DWIDIR=/data/gpfs/projects/punim2175/T-HEADS/mif/${ID}
TEMPDIR=/data/gpfs/projects/punim2175/T-HEADS/templates/pop_template_1_sites


# Step 1: Segment FODs and estimate FD
for site in FloreyPrisma FloreyVida MBI RCH ; do 
	fod2fixel -mask ${TEMPDIR}/template_mask.mif ${DWIDIR}/${site}/DWI_harmdwi/fod_in_poptemplate1_sites_space_NOT_REORIENTED.mif ${DWIDIR}/${site}/DWI_harmdwi/fixel_in_poptemplate1_sites_space_NOT_REORIENTED -afd fd.mif
done

# Step 2: Reorient fixels
for site in FloreyPrisma FloreyVida MBI RCH ; do 
	fixelreorient ${DWIDIR}/${site}/DWI_harmdwi/fixel_in_poptemplate1_sites_space_NOT_REORIENTED ${DWIDIR}/${site}/DWI_harmdwi/subject2poptemp1_sites_warp.mif ${DWIDIR}/${site}/DWI_harmdwi/fixel_in_poptemplate_1_space
	rm -r ${DWIDIR}/${site}/DWI_harmdwi/fixel_in_poptemplate1_sites_space_NOT_REORIENTED
done

# Step 3: Assign site to subject template fixels
for site in FloreyPrisma FloreyVida MBI RCH ; do 
	fixelcorrespondence ${DWIDIR}/${site}/DWI_harmdwi/fixel_in_poptemplate_1_space/fd.mif ${TEMPDIR}/fixel_mask ${TEMPDIR}/fd ${ID}_${site}.mif 
done

# Step 4: compute FC
for site in FloreyPrisma FloreyVida MBI RCH ; do 
	warp2metric ${DWIDIR}/${site}/DWI_harmdwi/subject2poptemp1_sites_warp.mif -fc ${TEMPDIR}/fixel_mask ${TEMPDIR}/fc ${ID}_${site}.mif
done

# unload modules
module unload MRtrix/3.0.4